services:
  - type: web
    name: tele-filter-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMINS
        sync: false
        
